# Generated by Django 2.1.7 on 2019-03-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipousuario',
        ),
        migrations.DeleteModel(
            name='tipoUsuario',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
