# Generated by Django 2.1.7 on 2019-05-02 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario_etiqueta',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='texto',
            field=models.TextField(default='Sin Comentario', max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comentario_Etiqueta',
        ),
        migrations.CreateModel(
            name='reporteProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.proveedor')),
                (
                'Usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
