# Generated by Django 2.1.7 on 2019-05-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario_etiqueta',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='texto',
            field=models.TextField(default='Sin Comentario', max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comentario_Etiqueta',
        ),
    ]
