# Generated by Django 2.1.7 on 2019-05-02 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20190501_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings_prov',
            name='comentario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ratingComment', to='proveedor.Comentario'),
            preserve_default=False,
        ),
    ]
