# Generated by Django 2.1.7 on 2019-05-01 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedor', '0003_ratings_prov_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='movimientos_pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoMovimiento', models.CharField(max_length=45)),
                ('FechaMovimiento', models.DateField()),
                ('HoraMovimiento', models.TimeField()),
                ('UsuarioMovimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
